[package]
name = "xokdinst"
version = "0.1.0"
authors = ["Colin Walters <walters@verbum.org>"]
edition = "2018"

[dependencies]
structopt = "0.2"
directories = "1.0"
failure = "0.1.1"
lazy_static = "1.2.0"

[[bin]]
name = "xokdinst"
path = "src/xokdinst.rs"